version: '3'

services:
    pgdatabase:
        image: postgres:15
        container_name: pgdatabase
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=nyc_motorvehicles
        volumes:
            - v_postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - airflow

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        volumes:
            - v_pgadmin:/var/lib/pgadmin
        ports:
            - "80:80"
        networks:
            - airflow
        depends_on:
            - pgdatabase
        
networks:
  airflow:
    external:
      name: nycmotorvehicle_default

volumes:
    v_pgadmin:
    v_postgres:
 